name: run_smoke_tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run tests
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          py -m pytest -v -s  fer4/test_smoke_free.py
